# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20180113_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
    ]
