# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_auto_20180113_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='topic',
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='topic', to='notebook.Topic'),
        ),
    ]
