# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_auto_20180113_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='paper',
        ),
        migrations.AddField(
            model_name='note',
            name='paper',
            field=models.ManyToManyField(blank=True, related_name='paper', to='notebook.Paper'),
        ),
    ]
