# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-07 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_auto_20180115_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='topic',
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
