# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-07 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_auto_20180807_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
