# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-08 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0011_note_prelims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
