# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-08 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0013_auto_20180808_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
