# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0015_auto_20180915_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='details',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='bullet',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bullet',
            name='meta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
