# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0016_auto_20180918_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='details',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
