# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-01 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0017_auto_20181101_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
